import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// Static metadata can't read the DB-backed favicon — generateMetadata can.
export async function generateMetadata(): Promise<Metadata> {
  let favicon: string | undefined;
  try {
    const res = await fetch(`${process.env.NEXT_PUBLIC_API_URL}/settings`, { cache: "no-store" });
    if (res.ok) {
      const data = await res.json();
      favicon = data.settings?.favicon || undefined;
    }
  } catch {
    // Fall back to the static app/favicon.ico convention.
  }

  return {
    title: "Create Next App",
    description: "Generated by create next app",
    icons: favicon ? { icon: favicon } : undefined,
  };
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">{children}</body>
    </html>
  );
}
